name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        branch: main

    - name: Set up Poetry
      run: |
        poetry --version
        if [ $? -ne 0 ]; then
          echo "Poetry not found, setting up..."
          python3 -m pip install --upgrade pip
          python3 -m pip install pipx --user
          python3 -m pipx ensurepath
          pipx install poetry
        fi
        poetry install --extras docs

    - name: Build and publish to pypi
    uses: JRubics/poetry-publish@v2.0
    with:
      pypi_token: ${{ secrets.PYPI_TOKEN }}